name: Backend CI Build, Test & Analize
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-test:
    name: Build, Test & Analyze Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build, Test & Analyze with Maven
        run: ./backend/mvnw -B -Dstyle.color=always verify --file backend/pom.xml